version: "3"

networks:
  monitor-net:
    driver: bridge

services:
    node-exporter:
        image: prom/node-exporter:v0.17.0
        container_name: node-exporter
        command:
            - '--path.procfs=/host/proc'
            - '--path.rootfs=/rootfs'
            - '--path.sysfs=/host/sys'
            - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        restart: unless-stopped
        ports:
            - "9100:9100"
        networks: 
            - monitor-net
    
    cadvisor:
        image: google/cadvisor:v0.32.0
        container_name: cadvisor
        command:
            - '--port=9110'
        volumes: 
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker:/var/lib/docker:ro
            - /dev/disk:/dev/disk:ro
        restart: unless-stopped
        ports: 
            - "9110:9110"
        networks: 
            - monitor-net
